# Multinomial Logistic Regression

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import random

In [2]:
%matplotlib inline

In [3]:
pd.options.display.max_rows = 40000
pd.options.display.max_columns = 40000

In [4]:
ds=pd.read_csv('train.csv')

### null items finder

In [5]:
dlist=[]
for items in ds.isnull().sum().iteritems():
    if items[1]>0:
        dlist.append(items[0])

### filling null items with median

In [6]:
for j in dlist:
    count=0
    for i in ds[j].value_counts().iteritems():
        count=count+1
        if count==1:
            ds[j].fillna(value=i[1],inplace=True)

In [7]:
ds=ds.drop(columns=['Cabin','Name','PassengerId','Ticket'])

In [8]:
sur=ds[['Survived']]

In [9]:
ds=ds.drop(columns=['Survived'])

### encoding categorical value

In [10]:
ds=pd.get_dummies(ds,columns=['Sex','Embarked'],drop_first=True)

In [11]:
dx=ds.copy()

### Feature Scaling

In [12]:
from sklearn.preprocessing import StandardScaler
sc_X=StandardScaler()
dx=sc_X.fit_transform(dx)

In [13]:
dx=dx.T

In [14]:
sur=sur.iloc[:,:].values

In [15]:
sur=sur.reshape(1,891)

## Logistic Regression as Neural Net

In [36]:
X=dx.copy()
Y=sur.copy()
#X=np.arange(50)
#X=X.reshape(5,10) # 5 features and 10 samples of data
W=np.random.randn(9,1) 
W=W.reshape(9,1) # 5 coefficient of features
#Y=np.array([0,1,0,1,0,1,1,0,1,1]) # 10 samples of target variable
#Y=Y.reshape(1,10)
b=np.random.randn(1,1)
for i in range(1000):
    Z=np.dot(W.T,X) + b # Z is of dimension 1x10
    A=1/(1+np.exp(-(Z))) # A is of dimension 1x10
    dz=A-Y # dz is of dimension 1x10 ???
    dw=(X@dz.T)*(1/891) # dw is of dimension 
    db=(1/891)*np.sum(dz) #??
    W=W-0.1*dw
    b=b-0.1*db
    print("*"*30)
    print(W)
    print(b)
    print("*"*30)

******************************
[[-0.56032373]
 [ 1.26122684]
 [ 1.47971744]
 [ 0.46409835]
 [ 0.77087427]
 [ 0.78415107]
 [-0.79915222]
 [ 0.63369216]
 [-0.3787547 ]]
[[1.3614261]]
******************************
******************************
[[-0.56492917]
 [ 1.24316766]
 [ 1.46825529]
 [ 0.4626733 ]
 [ 0.77308938]
 [ 0.75312897]
 [-0.78547006]
 [ 0.62630968]
 [-0.38623408]]
[[1.33384645]]
******************************
******************************
[[-0.56924967]
 [ 1.2251396 ]
 [ 1.4566558 ]
 [ 0.46106479]
 [ 0.77508191]
 [ 0.72255197]
 [-0.77210196]
 [ 0.61884903]
 [-0.39338785]]
[[1.30660317]]
******************************
******************************
[[-0.57329456]
 [ 1.20714998]
 [ 1.44492224]
 [ 0.45927545]
 [ 0.77685794]
 [ 0.69241554]
 [-0.75904206]
 [ 0.61131356]
 [-0.40022331]]
[[1.27969341]]
******************************
******************************
[[-0.5770732 ]
 [ 1.18920588]
 [ 1.43305796]
 [ 0.45730809]
 [ 0.77842354]
 [ 0.66271495]
 [-0.74628437]
 [ 0.60370674

******************************
******************************
[[-0.57485222]
 [-0.17243719]
 [-0.03222291]
 [-0.08893762]
 [ 0.41342623]
 [-1.00940476]
 [-0.2335575 ]
 [-0.09250524]
 [-0.42875262]]
[[-0.39231169]]
******************************
******************************
[[-0.57564556]
 [-0.17564406]
 [-0.03577886]
 [-0.08982838]
 [ 0.41155627]
 [-1.01241256]
 [-0.23304584]
 [-0.09382791]
 [-0.42841053]]
[[-0.39521177]]
******************************
******************************
[[-0.5764518 ]
 [-0.17880764]
 [-0.03928043]
 [-0.09069554]
 [ 0.40970593]
 [-1.0153806 ]
 [-0.2325419 ]
 [-0.0951287 ]
 [-0.42807529]]
[[-0.39806636]]
******************************
******************************
[[-0.57727059]
 [-0.18192865]
 [-0.04272881]
 [-0.0915397 ]
 [ 0.4078749 ]
 [-1.01830958]
 [-0.23204552]
 [-0.09640799]
 [-0.42774678]]
[[-0.40087633]]
******************************
******************************
[[-0.57810158]
 [-0.18500782]
 [-0.04612515]
 [-0.09236143]
 [ 0.40606288]
 [-1.02

******************************
[[-0.68227509]
 [-0.36386239]
 [-0.23577518]
 [-0.11695721]
 [ 0.28451573]
 [-1.18933187]
 [-0.20657728]
 [-0.15864151]
 [-0.41458718]]
[[-0.55117827]]
******************************
******************************
[[-0.68328901]
 [-0.36488274]
 [-0.2368103 ]
 [-0.11693262]
 [ 0.2836636 ]
 [-1.19026038]
 [-0.20647982]
 [-0.15887083]
 [-0.41456162]]
[[-0.55192111]]
******************************
******************************
[[-0.68430003]
 [-0.36589419]
 [-0.23783551]
 [-0.11690585]
 [ 0.28281593]
 [-1.19117972]
 [-0.20638419]
 [-0.159096  ]
 [-0.41453703]]
[[-0.55265602]]
******************************
******************************
[[-0.68530812]
 [-0.36689685]
 [-0.23885093]
 [-0.11687696]
 [ 0.28197268]
 [-1.19208999]
 [-0.20629034]
 [-0.15931708]
 [-0.41451341]]
[[-0.55338312]]
******************************
******************************
[[-0.68631326]
 [-0.36789083]
 [-0.23985668]
 [-0.11684598]
 [ 0.28113381]
 [-1.19299128]
 [-0.20619827]
 [-0.159

 [-0.41513719]]
[[-0.60010839]]
******************************
******************************
[[-0.77124777]
 [-0.43683816]
 [-0.30629028]
 [-0.10817558]
 [ 0.2138439 ]
 [-1.25147541]
 [-0.20274139]
 [-0.16839589]
 [-0.41516055]]
[[-0.60039729]]
******************************
******************************
[[-0.77192752]
 [-0.43730099]
 [-0.30670297]
 [-0.10806736]
 [ 0.21331619]
 [-1.2518304 ]
 [-0.20274165]
 [-0.16840721]
 [-0.41518408]]
[[-0.60068397]]
******************************
******************************
[[-0.77260435]
 [-0.43776076]
 [-0.30711229]
 [-0.1079591 ]
 [ 0.21279073]
 [-1.25218238]
 [-0.20274227]
 [-0.16841773]
 [-0.41520779]]
[[-0.60096847]]
******************************
******************************
[[-0.77327828]
 [-0.43821749]
 [-0.30751829]
 [-0.10785079]
 [ 0.21226751]
 [-1.2525314 ]
 [-0.20274324]
 [-0.16842747]
 [-0.41523167]]
[[-0.60125079]]
******************************
******************************
[[-0.7739493 ]
 [-0.43867122]
 [-0.30792097]
 [-0.

******************************
[[-0.8401175 ]
 [-0.47898516]
 [-0.34040439]
 [-0.09488148]
 [ 0.15996395]
 [-1.28063342]
 [-0.20441081]
 [-0.1663292 ]
 [-0.41905282]]
[[-0.6254278]]
******************************
******************************
[[-0.84049087]
 [-0.4791907 ]
 [-0.34054821]
 [-0.09479817]
 [ 0.15966847]
 [-1.28075756]
 [-0.20442833]
 [-0.16630366]
 [-0.41908337]]
[[-0.62554562]]
******************************
******************************
[[-0.84086254]
 [-0.47939507]
 [-0.34069093]
 [-0.09471513]
 [ 0.15937429]
 [-1.2808808 ]
 [-0.20444585]
 [-0.16627812]
 [-0.4191139 ]]
[[-0.62566275]]
******************************
******************************
[[-0.84123251]
 [-0.4795983 ]
 [-0.34083257]
 [-0.09463238]
 [ 0.15908142]
 [-1.28100316]
 [-0.20446339]
 [-0.16625258]
 [-0.41914442]]
[[-0.62577919]]
******************************
******************************
[[-0.84160079]
 [-0.47980038]
 [-0.34097313]
 [-0.0945499 ]
 [ 0.15878985]
 [-1.28112463]
 [-0.20448095]
 [-0.1662

******************************
******************************
[[-0.87353922]
 [-0.49653563]
 [-0.35148338]
 [-0.0870686 ]
 [ 0.13336011]
 [-1.29048258]
 [-0.2064056 ]
 [-0.1636854 ]
 [-0.42237437]]
[[-0.6354169]]
******************************
******************************
[[-0.87375884]
 [-0.49664545]
 [-0.35154376]
 [-0.08701528]
 [ 0.13318433]
 [-1.29053921]
 [-0.20642224]
 [-0.16366651]
 [-0.42240112]]
[[-0.63547914]]
******************************
******************************
[[-0.87397745]
 [-0.4967547 ]
 [-0.3516037 ]
 [-0.08696219]
 [ 0.13300935]
 [-1.29059548]
 [-0.20643887]
 [-0.16364771]
 [-0.42242783]]
[[-0.63554106]]
******************************
******************************
[[-0.87419505]
 [-0.49686337]
 [-0.35166319]
 [-0.08690933]
 [ 0.13283517]
 [-1.29065139]
 [-0.20645548]
 [-0.16362899]
 [-0.42245449]]
[[-0.63560265]]
******************************
******************************
[[-0.87441163]
 [-0.49697146]
 [-0.35172224]
 [-0.08685669]
 [ 0.13266179]
 [-1.290

 [-0.42516858]]
[[-0.64078099]]
******************************
******************************
[[-0.89312794]
 [-0.50605445]
 [-0.35616929]
 [-0.08225705]
 [ 0.11764088]
 [-1.29514535]
 [-0.208213  ]
 [-0.16205389]
 [-0.42519094]]
[[-0.64081552]]
******************************
******************************
[[-0.89325618]
 [-0.50611492]
 [-0.35619503]
 [-0.08222535]
 [ 0.11753771]
 [-1.29517335]
 [-0.20822782]
 [-0.16204423]
 [-0.42521326]]
[[-0.64084988]]
******************************
******************************
[[-0.89338381]
 [-0.50617507]
 [-0.35622059]
 [-0.08219379]
 [ 0.11743503]
 [-1.29520119]
 [-0.20824264]
 [-0.16203465]
 [-0.42523554]]
[[-0.64088406]]
******************************
******************************
[[-0.89351085]
 [-0.50623492]
 [-0.35624595]
 [-0.08216238]
 [ 0.11733282]
 [-1.29522886]
 [-0.20825744]
 [-0.16202514]
 [-0.42525779]]
[[-0.64091807]]
******************************
******************************
[[-0.89363729]
 [-0.50629447]
 [-0.35627113]
 [-0.

******************************
[[-0.90423629]
 [-0.51119968]
 [-0.3581292 ]
 [-0.07951833]
 [ 0.10869137]
 [-1.2974528 ]
 [-0.20978435]
 [-0.16137447]
 [-0.42747839]]
[[-0.64374506]]
******************************
******************************
[[-0.90431222]
 [-0.51123419]
 [-0.35814058]
 [-0.07949973]
 [ 0.1086301 ]
 [-1.29746776]
 [-0.20979791]
 [-0.16137152]
 [-0.42749745]]
[[-0.64376476]]
******************************
******************************
[[-0.90438779]
 [-0.51126852]
 [-0.35815188]
 [-0.07948122]
 [ 0.10856912]
 [-1.29748263]
 [-0.20981146]
 [-0.16136863]
 [-0.42751648]]
[[-0.64378436]]
******************************
******************************
[[-0.904463  ]
 [-0.51130269]
 [-0.3581631 ]
 [-0.0794628 ]
 [ 0.10850842]
 [-1.29749742]
 [-0.20982501]
 [-0.16136578]
 [-0.42753549]]
[[-0.64380386]]
******************************
******************************
[[-0.90453786]
 [-0.51133668]
 [-0.35817423]
 [-0.07944447]
 [ 0.10844801]
 [-1.29751214]
 [-0.20983854]
 [-0.161

******************************
******************************
[[-0.91186208]
 [-0.51461693]
 [-0.35911195]
 [-0.0776688 ]
 [ 0.10252796]
 [-1.29889884]
 [-0.21155984]
 [-0.16135532]
 [-0.42988086]]
[[-0.64569915]]
******************************
******************************
[[-0.91190186]
 [-0.51463448]
 [-0.35911614]
 [-0.07765929]
 [ 0.10249574]
 [-1.29890608]
 [-0.21157248]
 [-0.16135754]
 [-0.42989734]]
[[-0.64570921]]
******************************
******************************
[[-0.91194145]
 [-0.51465195]
 [-0.3591203 ]
 [-0.07764982]
 [ 0.10246367]
 [-1.29891328]
 [-0.2115851 ]
 [-0.16135979]
 [-0.4299138 ]]
[[-0.64571922]]
******************************
******************************
[[-0.91198086]
 [-0.51466934]
 [-0.35912443]
 [-0.0776404 ]
 [ 0.10243176]
 [-1.29892045]
 [-0.21159773]
 [-0.16136206]
 [-0.42993025]]
[[-0.64572917]]
******************************
******************************
[[-0.91202007]
 [-0.51468663]
 [-0.35912853]
 [-0.07763102]
 [ 0.10239999]
 [-1.29

### Converting sigmoid reverse

In [37]:
pred=np.dot(X.T,W)+b

In [38]:
cv=1/(1+np.exp(-(pred)))

In [39]:
l=[]
for i in cv:
    if i>=0.5:
        l.append(1)
    else:
        l.append(0)

In [40]:
g=sur.tolist()
t=[]
for i in g:
    for j in i:
        t.append(j)

In [41]:
len(l)

891

In [42]:
len(t)

891

### Evaluation Metrics

In [43]:
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 

In [44]:
confusion_matrix(t, l) 

array([[473,  76],
       [102, 240]], dtype=int64)

In [45]:
accuracy_score(t, l)

0.8002244668911336

## Matmul vs np.dot() vs *

In [42]:
a=np.arange(20)
a=a.reshape(4,5)
b=np.arange(20)
b=b.reshape(4,5)

### Matmul
It does matrix multiplication. and is same as np.dot for 2D array but for 3D array it differs.
# *
It does element-element wise multiplication. Also performs broadcasting operation


In [43]:
mtml=a@b # because dimension isnt matching

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 5)

In [44]:
mtml1=a@b.T

In [46]:
mtml1 # works because 4x5,5x4 =4x4

array([[  30,   80,  130,  180],
       [  80,  255,  430,  605],
       [ 130,  430,  730, 1030],
       [ 180,  605, 1030, 1455]])

In [47]:
multi=a*b

In [48]:
multi #element wise operation

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361]])

In [60]:
s=np.arange(4)
s=s.reshape(4,1)

In [53]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [61]:
s

array([[0],
       [1],
       [2],
       [3]])

In [63]:
a*s #s is broadcasted to become 4x5

array([[ 0,  0,  0,  0,  0],
       [ 5,  6,  7,  8,  9],
       [20, 22, 24, 26, 28],
       [45, 48, 51, 54, 57]])