In [274]:
import numpy as np
import pandas as pd

### **The target variable is weight of fish**

### Data Preprocessing 

In [275]:
# Reading csv file
ds_fish=pd.read_csv('Fish.csv')

In [276]:
# Seeing content of first 5 rows
ds_fish.head()

Species  Weight  Length1  Length2  Length3   Height   Width
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340

In [277]:
# Checking for null
ds_fish.isnull().sum()

Species    0
Weight     0
Length1    0
Length2    0
Length3    0
Height     0
Width      0
dtype: int64

In [278]:
# Shuffle the rows
ds_fish=ds_fish.sample(frac=1)

In [279]:
# List column name for further reference
list_of_columns=list(ds_fish)

In [280]:
# One-hot encoding
ds_fish=pd.get_dummies(ds_fish,columns=["Species"],drop_first=True)

In [281]:
ds_fish.shape

(159, 12)

In [282]:
# Splitting into train and validation set and target variable and independent variable
ds_fish_train_X=ds_fish.iloc[:120,1:].values
ds_fish_train_y=ds_fish.iloc[:120,0].values
ds_fish_val_X=ds_fish.iloc[120:,1:].values
ds_fish_val_y=ds_fish.iloc[120:,0].values

In [283]:
# To rank matrix to proper matrix
ds_fish_train_y=ds_fish_train_y.reshape(120,1)
ds_fish_val_y=ds_fish_val_y.reshape(39,1)

In [284]:
# Scaling
# It improves accuracy of model
# Can test it with or out without and see the result
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
ds_fish_train_X = sc.fit_transform(ds_fish_train_X)
ds_fish_val_X=sc.fit_transform(ds_fish_val_X)

In [285]:
ds_fish_train_X.shape

(120, 11)

# Multiple linear regression

In [330]:
def predicted_val(Xi,W,b):
    # to get result 150x1 of y_pred i.e 150 rows and 1 columns
    # (150,11)x(11,1)=(150,1)
    ypred=np.dot(Xi,W) + b
    return ypred

# Can implement using cost function as separate
# Here i have done directly

def Mul_Lin_Rg(X,y):
    W=np.random.randn(11,1)
    #W=np.ones((11,1))
    W=W.reshape(11,1)
    b=np.random.randn(1,1)
    #b=np.zeros((1,1))
    alpha=0.05
    epochs=1500
    for i in range(epochs):
        db=sum(predicted_val(X,W,b)-y)/(2*len(y))
        dW=(X.T@(predicted_val(X,W,b)-y))/(2*len(y))
        print(db.shape)
        print(db)
        print(dW.shape)
        print(dW)
        print("*"*80)
        b=b-alpha*db
        W=W-alpha*dW
    return b,W
# Some very important observation for fun
# Value of alpha,epochs seems very odd
# I have tested with lots and lots of hyper-parameter(alpha,epochs) value
# Done to play around tuning hyper-parameter manually and observe tendency of gradient descent
# Few observation
# 1. alpha= 0.5,epochs=300 ==>r2-squared:0.842...
# 2. alpha= 0.6,epochs=300 ==>r2-squared:0.8507...
# 3. alpha= 0.7,epochs=300 ==>r2-squared:0.8508...
# 4. alpha= 0.79,epochs=75 ==>r2-squared:0.871...
# 5. alpha= 0.79,epochs=76 ==>r2-squared:0.800...
# 6. alpha= 0.792,epochs=75 ==>r2-squared:0.87325...# Sweet spot of gradient descent
# But these above observation due to big value of alpha jumps around gradient descent a lot
# As i have traced it give a oscillating value of positive and negative of W's
# So, they may not be very decisive
# Instead use small value of alpha over lots of iteration
# 1.alpha=0.005, epochs=1000 ==>r2-squared:0.8968....
# 2.alpha=0.005, epochs=1500 ==>r2-Squared: 0.8902...# Sweet spot of gradient descent
# 2.alpha=0.005, epochs=2000 ==>r2-Squared: 0.8856...

#### Call Mul_Lin_Rg(ds_fish_train_X,ds_fish_train_y)

In [327]:
# Fitting obsessed multivariate regression
optimal_b,optimal_W=Mul_Lin_Rg(ds_fish_train_X,ds_fish_train_y)

(1,)
[-206.53492832]
(11, 1)
[[-164.19648215]
 [-164.83041424]
 [-165.86038987]
 [-132.0806208 ]
 [-160.37087024]
 [  38.65786984]
 [   1.15258615]
 [ -51.24908051]
 [  50.33696649]
 [  57.96827647]
 [  -3.6769942 ]]
********************************************************************************
(1,)
[-201.37155511]
(11, 1)
[[-144.4631436 ]
 [-145.00733112]
 [-145.883949  ]
 [-116.70335728]
 [-141.61875653]
 [  33.67027064]
 [   1.14978847]
 [ -42.95945281]
 [  44.99359632]
 [  47.369399  ]
 [  -2.90454156]]
********************************************************************************
(1,)
[-196.33726623]
(11, 1)
[[-127.1513202 ]
 [-127.61668923]
 [-128.35652974]
 [-103.18395915]
 [-125.1526731 ]
 [  29.28822054]
 [   1.14285914]
 [ -35.72608192]
 [  40.2678946 ]
 [  38.1309355 ]
 [  -2.23218131]]
********************************************************************************
(1,)
[-191.42883458]
(11, 1)
[[-111.96376144]
 [-112.35990781]
 [-112.97757926]
 [ -91.2951664 ]
 [-110.69

(1,)
[-13.75584862]
(11, 1)
[[-2.25948757]
 [-2.25325647]
 [-1.60523386]
 [ 1.44372345]
 [-1.65697094]
 [-2.90716718]
 [-1.19419192]
 [ 3.66654267]
 [-2.1605855 ]
 [-6.57457694]
 [ 0.09708717]]
********************************************************************************
(1,)
[-13.41195241]
(11, 1)
[[-2.24721296]
 [-2.24225225]
 [-1.59644372]
 [ 1.45457546]
 [-1.62981594]
 [-2.89612059]
 [-1.19825796]
 [ 3.62660136]
 [-2.1628245 ]
 [-6.4936437 ]
 [ 0.08734374]]
********************************************************************************
(1,)
[-13.0766536]
(11, 1)
[[-2.23499517]
 [-2.23130076]
 [-1.58774713]
 [ 1.46489622]
 [-1.60298184]
 [-2.88495308]
 [-1.20207004]
 [ 3.58736718]
 [-2.16457712]
 [-6.41400613]
 [ 0.07781172]]
********************************************************************************
(1,)
[-12.74973726]
(11, 1)
[[-2.22283443]
 [-2.2204021 ]
 [-1.57914272]
 [ 1.47469977]
 [-1.57646336]
 [-2.87366946]
 [-1.2056334 ]
 [ 3.54882517]
 [-2.16585953]
 [-6.3356395 

[-0.87094454]
(11, 1)
[[-1.25613137]
 [-1.35669373]
 [-1.01112355]
 [ 1.22034484]
 [ 0.09902791]
 [-1.58025743]
 [-0.91290385]
 [ 1.58365054]
 [-1.3592083 ]
 [-2.11224469]
 [-0.23759618]]
********************************************************************************
(1,)
[-0.84917092]
(11, 1)
[[-1.24972642]
 [-1.35097461]
 [-1.00786599]
 [ 1.21410829]
 [ 0.10797521]
 [-1.5698517 ]
 [-0.90814761]
 [ 1.57537659]
 [-1.35047031]
 [-2.09332937]
 [-0.23728214]]
********************************************************************************
(1,)
[-0.82794165]
(11, 1)
[[-1.24336346]
 [-1.34529282]
 [-1.00463333]
 [ 1.20787647]
 [ 0.1168399 ]
 [-1.55949994]
 [-0.90339811]
 [ 1.56719463]
 [-1.34176973]
 [-2.07461666]
 [-0.23694644]]
********************************************************************************
(1,)
[-0.80724311]
(11, 1)
[[-1.23704221]
 [-1.33964814]
 [-1.00142531]
 [ 1.20165021]
 [ 0.12562279]
 [-1.54920221]
 [-0.89865588]
 [ 1.55910322]
 [-1.33310694]
 [-2.05610368]
 [-0.2

(1,)
[-0.06258504]
(11, 1)
[[-0.77253254]
 [-0.92402119]
 [-0.77033867]
 [ 0.67411907]
 [ 0.69949198]
 [-0.77127336]
 [-0.50258366]
 [ 1.04129103]
 [-0.66800294]
 [-0.87429968]
 [-0.15771404]]
********************************************************************************
(1,)
[-0.06102041]
(11, 1)
[[-0.76929978]
 [-0.92111852]
 [-0.76872252]
 [ 0.67015318]
 [ 0.70288258]
 [-0.76585492]
 [-0.49963125]
 [ 1.03805736]
 [-0.66334793]
 [-0.86714913]
 [-0.15688521]]
********************************************************************************
(1,)
[-0.0594949]
(11, 1)
[[-0.76608782]
 [-0.91823431]
 [-0.76711594]
 [ 0.66621165]
 [ 0.70624033]
 [-0.76047385]
 [-0.49669727]
 [ 1.03484734]
 [-0.65872516]
 [-0.86005816]
 [-0.15605921]]
********************************************************************************
(1,)
[-0.05800753]
(11, 1)
[[-0.76289652]
 [-0.91536842]
 [-0.76551887]
 [ 0.66229438]
 [ 0.70956549]
 [-0.75512993]
 [-0.49378163]
 [ 1.03166073]
 [-0.65413444]
 [-0.8530262 ]
 [

(1,)
[-0.0051042]
(11, 1)
[[-0.53373622]
 [-0.70872778]
 [-0.64694983]
 [ 0.3834134 ]
 [ 0.91036555]
 [-0.38415219]
 [-0.28709742]
 [ 0.80667015]
 [-0.33594094]
 [-0.38563852]
 [-0.09209975]]
********************************************************************************
(1,)
[-0.00497659]
(11, 1)
[[-0.53198644]
 [-0.70714076]
 [-0.64599731]
 [ 0.38135162]
 [ 0.91150637]
 [-0.38147924]
 [-0.28557818]
 [ 0.80495234]
 [-0.33365252]
 [-0.3823977 ]
 [-0.09160786]]
********************************************************************************
(1,)
[-0.00485218]
(11, 1)
[[-0.53024692]
 [-0.70556286]
 [-0.6450493 ]
 [ 0.37930389]
 [ 0.91263233]
 [-0.37882566]
 [-0.28406948]
 [ 0.80324409]
 [-0.33138074]
 [-0.37918195]
 [-0.09111907]]
********************************************************************************
(1,)
[-0.00473087]
(11, 1)
[[-0.52851758]
 [-0.70399399]
 [-0.64410576]
 [ 0.37727013]
 [ 0.91374353]
 [-0.37619132]
 [-0.28257126]
 [ 0.80154532]
 [-0.32912549]
 [-0.37599105]
 [

(1,)
[-0.00033146]
(11, 1)
[[-0.39156815]
 [-0.57891459]
 [-0.56470677]
 [ 0.22548518]
 [ 0.96743565]
 [-0.18375872]
 [-0.17153105]
 [ 0.66393211]
 [-0.16452676]
 [-0.14728425]
 [-0.05397093]]
********************************************************************************
(1,)
[-0.00032317]
(11, 1)
[[-0.39059421]
 [-0.57801714]
 [-0.56409725]
 [ 0.22449849]
 [ 0.96749557]
 [-0.18254595]
 [-0.17081693]
 [ 0.66291923]
 [-0.16349012]
 [-0.1458749 ]
 [-0.05373195]]
********************************************************************************
(1,)
[-0.00031509]
(11, 1)
[[-0.38962505]
 [-0.57712393]
 [-0.56348987]
 [ 0.22351842]
 [ 0.96754924]
 [-0.18134204]
 [-0.17010776]
 [ 0.66191061]
 [-0.16246107]
 [-0.14447638]
 [-0.05349459]]
********************************************************************************
(1,)
[-0.00030721]
(11, 1)
[[-0.38866062]
 [-0.57623495]
 [-0.56288463]
 [ 0.22254492]
 [ 0.96759672]
 [-0.18014694]
 [-0.16940349]
 [ 0.66090624]
 [-0.16143954]
 [-0.14308861]
 

[-2.77254319e-05]
(11, 1)
[[-0.31451313]
 [-0.50736297]
 [-0.51336082]
 [ 0.15408071]
 [ 0.95016406]
 [-0.09866739]
 [-0.12042465]
 [ 0.58116553]
 [-0.09180043]
 [-0.05018916]
 [-0.03682488]]
********************************************************************************
(1,)
[-2.70322961e-05]
(11, 1)
[[-0.3138801 ]
 [-0.50676973]
 [-0.5129081 ]
 [ 0.15356034]
 [ 0.94980504]
 [-0.09807581]
 [-0.12005836]
 [ 0.58045915]
 [-0.0912948 ]
 [-0.04953286]
 [-0.03670188]]
********************************************************************************
(1,)
[-2.63564887e-05]
(11, 1)
[[-0.31324951]
 [-0.50617868]
 [-0.51245654]
 [ 0.15304323]
 [ 0.94944331]
 [-0.09748854]
 [-0.11969449]
 [ 0.57975498]
 [-0.09079284]
 [-0.04888174]
 [-0.0365797 ]]
********************************************************************************
(1,)
[-2.56975764e-05]
(11, 1)
[[-0.31262135]
 [-0.50558979]
 [-0.51200613]
 [ 0.15252935]
 [ 0.94907891]
 [-0.09690554]
 [-0.11933303]
 [ 0.57905301]
 [-0.09029453]
 [-0.

[-2.31915968e-06]
(11, 1)
[[-0.26198126]
 [-0.45775359]
 [-0.47363397]
 [ 0.11554188]
 [ 0.90526482]
 [-0.05707114]
 [-0.09377478]
 [ 0.52067478]
 [-0.05623758]
 [-0.00550609]
 [-0.02789171]]
********************************************************************************
(1,)
[-2.2611807e-06]
(11, 1)
[[-0.26152552]
 [-0.45731962]
 [-0.473269  ]
 [ 0.11525131]
 [ 0.90473317]
 [-0.05678083]
 [-0.09357885]
 [ 0.52013233]
 [-0.05598925]
 [-0.00521035]
 [-0.02782625]]
********************************************************************************
(1,)
[-2.20465117e-06]
(11, 1)
[[-0.26107108]
 [-0.45688682]
 [-0.4729047 ]
 [ 0.11496235]
 [ 0.9042005 ]
 [-0.0564926 ]
 [-0.09338411]
 [ 0.51959112]
 [-0.0557427 ]
 [-0.00491709]
 [-0.02776119]]
********************************************************************************
(1,)
[-2.14953488e-06]
(11, 1)
[[-0.26061794]
 [-0.4564552 ]
 [-0.47254108]
 [ 0.11467499]
 [ 0.90366683]
 [-0.05620645]
 [-0.09319055]
 [ 0.51905113]
 [-0.05549792]
 [-0.0

********************************************************************************
(1,)
[-1.46836439e-07]
(11, 1)
[[-0.21857549]
 [-0.41613346]
 [-0.43725439]
 [ 0.09135106]
 [ 0.84333733]
 [-0.0350239 ]
 [-0.07791381]
 [ 0.46760335]
 [-0.03736355]
 [ 0.01537466]
 [-0.02261638]]
********************************************************************************
(1,)
[-1.43165534e-07]
(11, 1)
[[-0.21822491]
 [-0.415795  ]
 [-0.43694769]
 [ 0.09118337]
 [ 0.84274746]
 [-0.03489031]
 [-0.07780791]
 [ 0.46716352]
 [-0.03724902]
 [ 0.01548548]
 [-0.02258139]]
********************************************************************************
(1,)
[-1.39586389e-07]
(11, 1)
[[-0.21787503]
 [-0.41545719]
 [-0.4366414 ]
 [ 0.09101642]
 [ 0.84215743]
 [-0.03475765]
 [-0.07770256]
 [ 0.4667244 ]
 [-0.0371353 ]
 [ 0.01559522]
 [-0.02254659]]
********************************************************************************
(1,)
[-1.36096731e-07]
(11, 1)
[[-0.21752584]
 [-0.41512001]
 [-0.43633554]
 [ 0.0908

[-1.10994994e-08]
(11, 1)
[[-0.18589412]
 [-0.38444267]
 [-0.40789477]
 [ 0.07736792]
 [ 0.78301313]
 [-0.02521272]
 [-0.06935817]
 [ 0.42593661]
 [-0.02893841]
 [ 0.02227262]
 [-0.01980676]]
********************************************************************************
(1,)
[-1.08220219e-08]
(11, 1)
[[-0.18559995]
 [-0.38415625]
 [-0.40762412]
 [ 0.07725572]
 [ 0.78242593]
 [-0.02514627]
 [-0.06929203]
 [ 0.42555605]
 [-0.02888119]
 [ 0.02230631]
 [-0.01978521]]
********************************************************************************
(1,)
[-1.05514693e-08]
(11, 1)
[[-0.18530621]
 [-0.38387023]
 [-0.40735377]
 [ 0.07714391]
 [ 0.7818389 ]
 [-0.02508027]
 [-0.06922617]
 [ 0.42517596]
 [-0.02882435]
 [ 0.02233949]
 [-0.01976374]]
********************************************************************************
(1,)
[-1.02876856e-08]
(11, 1)
[[-0.18501291]
 [-0.38358461]
 [-0.40708371]
 [ 0.07703248]
 [ 0.78125205]
 [-0.0250147 ]
 [-0.06916056]
 [ 0.42479635]
 [-0.02876788]
 [ 0.

[-6.51344934e-10]
(11, 1)
[[-0.1553039 ]
 [-0.35456931]
 [-0.37927884]
 [ 0.06670644]
 [ 0.71870641]
 [-0.01990191]
 [-0.06327218]
 [ 0.38595898]
 [-0.02434826]
 [ 0.0236985 ]
 [-0.01783791]]
********************************************************************************
(1,)
[-6.35046386e-10]
(11, 1)
[[-0.15504954]
 [-0.35432026]
 [-0.37903747]
 [ 0.06662506]
 [ 0.71814825]
 [-0.01986927]
 [-0.06322726]
 [ 0.38562364]
 [-0.02431988]
 [ 0.0236954 ]
 [-0.0178235 ]]
********************************************************************************
(1,)
[-6.19177124e-10]
(11, 1)
[[-0.15479547]
 [-0.35407148]
 [-0.37879633]
 [ 0.06654387]
 [ 0.71759041]
 [-0.01983683]
 [-0.06318246]
 [ 0.38528865]
 [-0.02429167]
 [ 0.02369209]
 [-0.01780913]]
********************************************************************************
(1,)
[-6.03675569e-10]
(11, 1)
[[-0.15454169]
 [-0.35382297]
 [-0.37855543]
 [ 0.06646288]
 [ 0.71703289]
 [-0.01980458]
 [-0.06313779]
 [ 0.38495401]
 [-0.02426362]
 [ 0.

********************************************************************************
(1,)
[-3.63120497e-11]
(11, 1)
[[-0.12801285]
 [-0.32780045]
 [-0.35315218]
 [ 0.05845755]
 [ 0.65726824]
 [-0.01715639]
 [-0.05882111]
 [ 0.34978766]
 [-0.02194435]
 [ 0.02238367]
 [-0.0164188 ]]
********************************************************************************
(1,)
[-3.54161737e-11]
(11, 1)
[[-0.12778732]
 [-0.32757889]
 [-0.35293465]
 [ 0.05839276]
 [ 0.65674969]
 [-0.01713895]
 [-0.05878687]
 [ 0.3494874 ]
 [-0.02192892]
 [ 0.02236599]
 [-0.01640795]]
********************************************************************************
(1,)
[-3.45388903e-11]
(11, 1)
[[-0.12756201]
 [-0.32735754]
 [-0.35271731]
 [ 0.05832808]
 [ 0.6562315 ]
 [-0.01712159]
 [-0.05875269]
 [ 0.34918741]
 [-0.02191357]
 [ 0.02234824]
 [-0.01639713]]
********************************************************************************
(1,)
[-3.36832784e-11]
(11, 1)
[[-0.12733692]
 [-0.32713641]
 [-0.35250016]
 [ 0.0582

(1,)
[-2.21724861e-12]
(11, 1)
[[-0.10423864]
 [-0.30442079]
 [-0.33011856]
 [ 0.05183692]
 [ 0.60193903]
 [-0.0156351 ]
 [-0.05536083]
 [ 0.3180541 ]
 [-0.02058452]
 [ 0.02010944]
 [-0.01532726]]
********************************************************************************
(1,)
[-2.147497e-12]
(11, 1)
[[-0.1040353 ]
 [-0.30422064]
 [-0.3299208 ]
 [ 0.05178181]
 [ 0.601461  ]
 [-0.01562434]
 [-0.05533228]
 [ 0.3177821 ]
 [-0.02057477]
 [ 0.02008707]
 [-0.01531829]]
********************************************************************************
(1,)
[-2.10107487e-12]
(11, 1)
[[-0.10383214]
 [-0.30402066]
 [-0.3297232 ]
 [ 0.05172677]
 [ 0.60098333]
 [-0.01561363]
 [-0.05530377]
 [ 0.31751032]
 [-0.02056506]
 [ 0.02006468]
 [-0.01530933]]
********************************************************************************
(1,)
[-2.04825786e-12]
(11, 1)
[[-0.10362917]
 [-0.30382085]
 [-0.32952577]
 [ 0.0516718 ]
 [ 0.60050602]
 [-0.01560295]
 [-0.0552753 ]
 [ 0.31723879]
 [-0.02055539]
 [

[-5.45459973e-13]
(11, 1)
[[-0.08365196]
 [-0.28414269]
 [-0.31004893]
 [ 0.04634826]
 [ 0.55325717]
 [-0.01467503]
 [-0.05252643]
 [ 0.29048098]
 [-0.01970433]
 [ 0.01767795]
 [-0.01443902]]
********************************************************************************
(1,)
[-5.30420152e-13]
(11, 1)
[[-0.08346664]
 [-0.28396002]
 [-0.30986787]
 [ 0.04629956]
 [ 0.55281673]
 [-0.01466735]
 [-0.05250132]
 [ 0.2902325 ]
 [-0.01969719]
 [ 0.01765481]
 [-0.01443116]]
********************************************************************************
(1,)
[-5.35512375e-13]
(11, 1)
[[-0.08328147]
 [-0.2837775 ]
 [-0.30968697]
 [ 0.04625091]
 [ 0.55237663]
 [-0.0146597 ]
 [-0.05247623]
 [ 0.28998422]
 [-0.01969007]
 [ 0.01763168]
 [-0.01442332]]
********************************************************************************
(1,)
[-5.36222918e-13]
(11, 1)
[[-0.08309646]
 [-0.28359514]
 [-0.30950621]
 [ 0.0462023 ]
 [ 0.55193688]
 [-0.01465206]
 [-0.05245117]
 [ 0.28973615]
 [-0.01968297]
 [ 0.

(1,)
[-5.40130903e-13]
(11, 1)
[[-0.06451989]
 [-0.26527434]
 [-0.29133001]
 [ 0.04136852]
 [ 0.50764242]
 [-0.01394225]
 [-0.04995541]
 [ 0.26481141]
 [-0.01901504]
 [ 0.01521306]
 [-0.01363654]]
********************************************************************************
(1,)
[-5.4534155e-13]
(11, 1)
[[-0.06435076]
 [-0.26510745]
 [-0.29116431]
 [ 0.04132487]
 [ 0.50723807]
 [-0.01393621]
 [-0.04993282]
 [ 0.26458436]
 [-0.01900928]
 [ 0.01519071]
 [-0.0136295 ]]
********************************************************************************
(1,)
[-5.4534155e-13]
(11, 1)
[[-0.06418177]
 [-0.2649407 ]
 [-0.29099874]
 [ 0.04128127]
 [ 0.50683403]
 [-0.01393017]
 [-0.04991025]
 [ 0.26435749]
 [-0.01900353]
 [ 0.01516838]
 [-0.01362247]]
********************************************************************************
(1,)
[-5.33972866e-13]
(11, 1)
[[-0.06401293]
 [-0.26477408]
 [-0.2908333 ]
 [ 0.04123771]
 [ 0.50643032]
 [-0.01392415]
 [-0.0498877 ]
 [ 0.26413082]
 [-0.01899779]
 [

In [328]:
# Predicting on validation
ypred_on_val=predicted_val(ds_fish_val_X,optimal_W,optimal_b)

In [329]:
# Checking accuracy by r_squared
def r2(y_val,y):
    sst = np.sum((y-y.mean())**2)
    ssr = np.sum((y_val-y)**2)
    r2 = 1-(ssr/sst)
    return(r2)

r2(ypred_on_val,ds_fish_val_y)

0.9006159756520129

## Make your life easy with sklearn

In [628]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()  
regressor.fit(ds_fish_train_X,ds_fish_train_y) #training the algorithm

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [629]:
# Predicting Value
y_pred = regressor.predict(ds_fish_val_X)

In [630]:
from sklearn.metrics import r2_score
r2_score(ds_fish_val_y,y_pred)
# HAHA sklearn failed before my obsession over hyperparameter

0.8522290597361759

In [224]:
i=np.ones((11,1))

In [225]:
i

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])