In [1]:
import numpy as np
import pandas as pd
import os 
import zipfile


# **The target variable is weight of fish**

## Data Preprocessing 

In [91]:
# Reading csv file
ds_fish=pd.read_excel('pp.xlsx')

In [94]:
ds_fish.shape

(9568, 5)

In [92]:
# Seeing content of first 5 rows
ds_fish.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [93]:
# Checking for null
ds_fish.isnull().sum()

AT    0
V     0
AP    0
RH    0
PE    0
dtype: int64

In [95]:
ds_fish.tail()

AT      V       AP     RH      PE
9563  16.65  49.69  1014.01  91.00  460.03
9564  13.19  39.18  1023.67  66.78  469.62
9565  31.32  74.33  1012.92  36.48  429.57
9566  24.48  69.45  1013.86  62.39  435.74
9567  21.60  62.52  1017.23  67.87  453.28

In [96]:
# Shuffle the rows
ds_fish=ds_fish.sample(frac=1)

In [97]:
# List column name for further reference
list_of_columns=list(ds_fish)

In [98]:
ds_fish.shape

(9568, 5)

In [102]:
# Splitting into train and validation set and target variable and independent variable
ds_fish_train_X=ds_fish.iloc[:9000,:-1].values
ds_fish_train_y=ds_fish.iloc[:9000,4].values
ds_fish_val_X=ds_fish.iloc[9000:,:-1].values
ds_fish_val_y=ds_fish.iloc[9000:,4].values

In [103]:
# Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
ds_fish_train_X = sc.fit_transform(ds_fish_train_X)
ds_fish_val_X=sc.fit_transform(ds_fish_val_X)

In [105]:
ds_fish_val_y.shape

(568,)

In [106]:
# To rank matrix to proper matrix
ds_fish_train_y=ds_fish_train_y.reshape(9000,1)
ds_fish_val_y=ds_fish_val_y.reshape(568,1)

In [107]:
ds_fish_train_X.shape

(9000, 4)

#### **Have not performed any scaling**
#### **Just to implement the model from scratch**
#### **Add this code to perform scaling**
"""
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)
"""
#### X is the independent variable matrix

# Multiple linear regression

In [292]:
def predicted_val(Xi,W,b):
    # to get result 150x1 of y_pred i.e 150 rows and 1 columns
    # (150,11)x(11,1)=(150,1)
    ypred=np.dot(Xi,W) + b
    return ypred


def Mul_Lin_Rg(X,y):
    W=np.random.randn(4,1)
    W=W.reshape(4,1)
    b=np.random.randn(1,1)
    alpha=0.02
    epochs=1000
    for i in range(epochs):
        db=sum(predicted_val(X,W,b)-y)/(2*len(y))
        dW=(X.T@(predicted_val(X,W,b)-y))/(2*len(y))
        b=b-alpha*db
        W=W-alpha*dW
    return b,W

In [293]:
ypred.shape

NameError: name 'ypred' is not defined

## Call Mul_Lin_Rg(ds_fish_train_X,ds_fish_train_y)

In [294]:
optimal_b,optimal_W=Mul_Lin_Rg(ds_fish_train_X,ds_fish_train_y)

In [295]:
# Predicting on validation
ypred_on_val=predicted_val(ds_fish_val_X,optimal_W,optimal_b)

In [296]:
ypred_on_val

array([[476.57822738],
       [471.63081988],
       [435.83657982],
       [425.83681777],
       [448.5832055 ],
       [464.17377506],
       [470.91187663],
       [465.0747782 ],
       [468.70884851],
       [475.54433331],
       [452.08749892],
       [470.58939596],
       [467.88714479],
       [443.22831726],
       [437.62564409],
       [472.43732114],
       [470.67671666],
       [431.31701668],
       [439.85792963],
       [445.71499295],
       [443.74461836],
       [461.02372636],
       [468.07019405],
       [471.08810907],
       [466.25401168],
       [440.06898272],
       [452.02337368],
       [427.33792332],
       [457.58094913],
       [431.03620927],
       [449.22561361],
       [475.7620878 ],
       [436.00966137],
       [444.29145343],
       [452.18517377],
       [424.34370479],
       [430.96392863],
       [441.05023625],
       [452.42354052],
       [472.9457007 ],
       [471.30955661],
       [430.95733612],
       [458.44225244],
       [432

In [297]:
ds_fish_val_y

array([[478.88],
       [486.55],
       [437.5 ],
       [433.32],
       [451.86],
       [463.3 ],
       [469.03],
       [466.59],
       [470.33],
       [483.38],
       [452.38],
       [469.04],
       [477.93],
       [448.8 ],
       [448.26],
       [485.76],
       [479.23],
       [435.38],
       [439.71],
       [449.76],
       [443.71],
       [464.12],
       [466.15],
       [475.43],
       [475.72],
       [452.47],
       [451.49],
       [436.85],
       [463.14],
       [434.48],
       [447.02],
       [485.12],
       [446.94],
       [452.21],
       [450.6 ],
       [433.74],
       [435.65],
       [447.93],
       [449.67],
       [481.05],
       [475.48],
       [429.99],
       [454.4 ],
       [438.41],
       [465.58],
       [450.89],
       [442.28],
       [470.27],
       [440.29],
       [465.89],
       [476.02],
       [445.72],
       [460.38],
       [450.5 ],
       [459.85],
       [479.43],
       [482.16],
       [452.15],
       [451.33

In [298]:
optimal_b.shape

(1, 1)

In [299]:
# Checking accuracy by r_squared
def r2(y_val,y):
    sst = np.sum((y-y.mean())**2)
    ssr = np.sum((y_val-y)**2)
    r2 = 1-(ssr/sst)
    return(r2)

acc=r2(ypred_on_val,ds_fish_val_y)

In [300]:
acc

0.8484206405385956

In [72]:
v=np.random.randn(150,11)
th=np.random.randn(11,1)
t=np.dot(v,th)

In [73]:
t.shape

(150, 1)

In [23]:
correlation_matrix = np.corrcoef(ypred_on_val, ds_fish_val_y)
correlation_xy = correlation_matrix[0,1]
r_squared = correlation_xy**2
print(r_squared)

nan


C:\Users\Ankan\Anaconda3\lib\site-packages\numpy\lib\function_base.py:2522: RuntimeWarning: Degrees of freedom <= 0 for slice
  c = cov(x, y, rowvar)
C:\Users\Ankan\Anaconda3\lib\site-packages\numpy\lib\function_base.py:2451: RuntimeWarning: divide by zero encountered in true_divide
  c *= np.true_divide(1, fact)
C:\Users\Ankan\Anaconda3\lib\site-packages\numpy\lib\function_base.py:2451: RuntimeWarning: invalid value encountered in multiply
  c *= np.true_divide(1, fact)


In [39]:
from sklearn.metrics import r2_score

In [40]:
r2_score(ds_fish_val_y,ypred_on_val)

-1.0185388209856889e+20

In [14]:
abs(-98)

98

In [84]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()  
regressor.fit(ds_fish_train_X,ds_fish_train_y) #training the algorithm

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [85]:
y_pred = regressor.predict(ds_fish_val_X)

In [86]:
r2_score(ds_fish_val_y,y_pred)

0.6589875411644874

In [87]:
y_pred

array([[ 601.46410505],
       [ 355.83761818],
       [-111.8453988 ],
       [ 948.46780291],
       [  -7.11076291],
       [ 428.84569395],
       [-162.58224043],
       [ 360.86506863],
       [1111.59211342]])

In [88]:
ds_fish_train_y

array([[ 725. ],
       [ 145. ],
       [  32. ],
       [ 120. ],
       [1250. ],
       [ 188. ],
       [ 170. ],
       [ 700. ],
       [  12.2],
       [1600. ],
       [  70. ],
       [ 800. ],
       [ 161. ],
       [ 500. ],
       [ 300. ],
       [  19.7],
       [ 456. ],
       [ 260. ],
       [ 650. ],
       [  78. ],
       [1100. ],
       [ 242. ],
       [   8.7],
       [1000. ],
       [ 850. ],
       [ 340. ],
       [ 200. ],
       [ 600. ],
       [  19.9],
       [ 685. ],
       [ 475. ],
       [ 610. ],
       [ 180. ],
       [ 620. ],
       [ 575. ],
       [ 160. ],
       [ 272. ],
       [ 556. ],
       [ 140. ],
       [ 540. ],
       [ 125. ],
       [  69. ],
       [ 500. ],
       [ 900. ],
       [ 265. ],
       [ 130. ],
       [  60. ],
       [ 500. ],
       [  51.5],
       [ 110. ],
       [1650. ],
       [  85. ],
       [ 135. ],
       [ 514. ],
       [1100. ],
       [ 180. ],
       [ 650. ],
       [1000. ],
       [ 345. 

In [100]:
l=[7,8,9,6,5]


In [101]:
l[4]

5

In [ ]:
4